// AUTO-GENERATED by scripts/generate-docs-index.mjs — DO NOT EDIT MANUALLY
// Regenerate with: node scripts/generate-docs-index.mjs

export interface AutoGenDocItem {
  slug: string;
  title: string;
  fileName: string;
}

export interface AutoGenNavSection {
  title: string;
  items: AutoGenDocItem[];
}

export interface AutoGenSearchItem {
  slug: string;
  title: string;
  fileName: string;
  section: string;
  content: string;
  headings: string[];
}

export const autoNavSections: AutoGenNavSection[] = [];

export const autoSearchIndex: AutoGenSearchItem[] = [];

export const autoAllSlugs: string[] = [];
